### ISSUE TITLE
Socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by dersuchendee** [mitkrieg/dash_demo#2]
Here is the error I get:

```
Dash is running on http://127.0.01:5000/

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "C:\Users\annas\PycharmProjects\ADHO\index.py", line 34, in <module>
    app.run_server(port=5000, host= '127.0.01',debug=False)
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\dash\dash.py", line 1750, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 1052, in run_simple
    inner()
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 996, in inner
    srv = make_server(
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno 11001] getaddrinfo failed

```
Maybe I'm doing something wrong, but I can't get it right...

**Comment by mitkrieg** [comment]
@dersuchendee try `debug = True` instead of false. Do you still get the same error?

**Comment by alikaz3mi** [comment]
Thank you for sharing your code and great tutorial. I solved this issue by removing host and port in `app.run_server`, besides setting `debug=False`.
